services:
  server: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file: 
    - .env
  db:
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=edifismart
    volumes:
      -  pgdata:/var/lib/postgresql/data

volumes:
  pgdata: