services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=edifismart
  db:
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=edifismart
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
